# Houses of Westeros Linting Rules

excluded:
  - ${PWD}/Carthage
  - ${PWD}/Pods
  - ${PWD}/DerivedData

disabled_rules:
  - discarded_notification_center_observer
  - notification_center_detachment
  - orphaned_doc_comment
  - unused_capture_list

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon # promote to error
  - comma_inheritance
  - convenience_type
  - discouraged_assert
  - discouraged_object_literal
  - discouraged_none_name
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - file_name_no_space
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - switch_case_on_newline
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_import
  - unused_optional_binding
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  - weak_delegate

custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] .+ = (\[.+\]\(\))'
    capture_group: 1
    message: "Use explicit type annotation when initializing empty arrays and dictionaries."
    severity: warning

  auto_generated_leftovers:
    regex: 'func [^\n]*\{\n(\s*super\.[^\n]*\n(\s*\/\/[^\n]*\n)*|(\s*\/\/[^\n]*\n)+)\s*\}'
    message: "Delete auto-generated functions that you don't use."

  already_true:
    regex: "== true"
    message: "Don't compare to true, use the bool value."

  already_false:
    regex: "== false"
    message: "Don't compare to false, use !value."

  #commented_out_code:
  #  regex: '(?=&lt;!:|\/)\/\/\h*[a-z.](?!wiftlint)'
  #  message: "Comment starting with lowercase letter - did you forget to delete old code?"

  multiline_commented_out_code:
    regex: '^\s*[a-z]'
    match_kinds: comment
    message: "Comment starting with lowercase letter - did you forget to delete old code?"

  avoid_anyview:
    regex: 'AnyView'
    message: "Avoid using AnyView - use @ViewBuilder instead."

  avoid_multiline_comment_markers:
    regex: '\*/'
    message: "Avoid using multi-line comment markers like */ and /* - use // and /// instead."

  avoid_background_color:
    regex: '\.background\(Color\.'
    message: "Avoid using .background(Color), use .backgroundColor() instead."

  use_int_zero_property_in_initialization:
    regex: ' = 0'
    message: "Avoid using initializing an int to '0', use .zero instead."

  use_int_zero_property_in_single_check:
    regex: ' == 0[^( {)]'
    message: "Avoid checking for '0' in single check, use '== .zero' instead."

attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"

force_cast: warning
force_try: warning
function_body_length:
    warning: 60

legacy_hashing: error

identifier_name:
  excluded:
    - i
    - id
    - x
    - y
    - z
    - r
    - g
    - b
    - a

indentation_width:
  indentation_width: 2

line_length:
  ignores_urls: true
  ignores_function_declarations: false
  ignores_comments: false

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true
  
private_over_fileprivate:
  validate_extensions: true

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2